### PR TITLE
Multiple code improvements - squid:S1213, squid:S134, squid:S1066, squid:S2130

### PR DESCRIPTION
**Pull request by georgekankava**
This pull request is focused on resolving occurrences of Sonar rules
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
squid:S134 - Control flow statements "if", "for", "while", "switch" and "try" should not be nested too deeply.
squid:S1066 - Collapsible "if" statements should be merged.
squid:S2130 - Parsing should be used to convert "Strings" to primitives.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1213
https://dev.eclipse.org/sonar/rules/show/squid:S134
https://dev.eclipse.org/sonar/rules/show/squid:S1066
https://dev.eclipse.org/sonar/rules/show/squid:S2130
Please let me know if you have any questions.
George Kankava

### CODE REVIEW

**Comment by mfaure** [comment]
Hi @georgekankava thank you for the contribution. Could you please base your PR against the `develop` branch ? (Thanks !)

**Comment by georgekankava** [comment]
@mfaure Are we merging this pull request?

**Comment by mfaure** [comment]
@georgekankava Sure! But as I mentioned in the previous comment, would you be able to place it the `develop` branch ?

**Comment by georgekankava** [comment]
@mfaure I have created the same pull request agains develop so we can close this.

**Pull request closed without merging**
